### ISSUE TITLE
Error in DBpediaSpotlightClient

### ISSUE THREAD

**Issue by dafnevk** [ixa-ehu/ixa-pipe-ned#2]
When running this module (as part of the vu-rm-pip3 pipeline), I get the following error:
```
-- Running ixa-pipe-ned
launching dbpedia spotlight server
waiting for connection...
waiting for connection...
INFO 2020-02-07 13:51:49,369 main [DBpediaSpotlightClient] - Querying API.
ERROR 2020-02-07 13:51:53,742 main [DBpediaSpotlightClient] - Method failed: HTTP/1.1 500 Internal Error
component ixa-pipe-ned failed
```

Any pointers to where this error could come from?

**Comment by ragerri** [comment]
There were not any other details or traces in the error output?

**Comment by dafnevk** [comment]
No, this is all the information I get, so it is unclear to me in which request this error happens. Also, the code seems to continue running because I do get a NAF file as output.
Is there any way to get more verbose output from the annotater?

I'm running now the jar file directly:
`java -jar lib/java/ixa-pipe-ned-1.1.6.jar -p 2060 -i lib/resources/spotlight/wikipedia-db -n nlEn < test-in.naf > test-out.naf`

**Comment by dafnevk** [comment]
It seems the problem is in the installation of Spotlight, in the logs of the Spotlight server I get:
```
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at com.sun.jersey.server.impl.wadl.WadlFactory.init(WadlFactory.java:100)
        at com.sun.jersey.server.impl.application.RootResourceUriRules.initWadl(RootResourceUriRules.java:169)
        at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:106)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1298)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:169)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:775)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:771)
        at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:771)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:766)
        at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:488)
        at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:318)
        at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:609)
        at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:210)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:373)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:556)
        at javax.servlet.GenericServlet.init(GenericServlet.java:258)
        at com.sun.grizzly.http.servlet.ServletAdapter.loadServlet(ServletAdapter.java:486)
        at com.sun.grizzly.http.servlet.ServletAdapter.doService(ServletAdapter.java:425)
        at com.sun.grizzly.http.servlet.ServletAdapter.service(ServletAdapter.java:379)
        at com.sun.grizzly.tcp.http11.GrizzlyAdapter.service(GrizzlyAdapter.java:179)
        at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:849)
        at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:746)
        at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1045)
        at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:228)
        at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
        at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
        at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
        at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
        at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 35 more

```
I used the installation scripts of the `vu-rm-pip3` pipeline, which gives me dbpedia-spotlight v0.7.1. My java version is OpenJDK 11.0.8.

**Comment by dafnevk** [comment]
Probably my java version is the problem: https://github.com/dbpedia-spotlight/dbpedia-spotlight-model/issues/37
